version: 2.1

orbs:
  node: circleci/node@5
  cypress: cypress-io/cypress@3

jobs:
  test:
    docker:
      - image: cypress/browsers:node18.12.0-chrome107-ff106
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests after starting server
          start-command: npm run test:ci

workflows:
  test-workflow:
    jobs:
      - test