name: Parallet Test Execution
on: push

jobs:
  Register-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:register
    
      - name: Cypress Test Reports
        uses: actions/upload-artifact@v4
        with: 
            name: mochawesome-report - Register flow
            path: cypress/reports/html

  Add-To-Cart-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:addToCart

      - name: Cypress Test Reports
        uses: actions/upload-artifact@v4
        with: 
            name: mochawesome-report - Add to cart flow
            path: cypress/reports/html

            