name: Parallet Test Automation
on: push

jobs:
  Register-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:register

  Add-To-Cart-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:addToCart
